# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:             Mahsa Saeidi
tagline:          'A Jekyll theme'
description:      ''
url:              http://gitmahsa.ghihub.io
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
plugins:
  - jekyll-paginate
  - jekyll-gist
  - kramdown
